apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beskar7-system

resources:
- ../../default
- pdb.yaml  # Keep the existing PDB

patchesStrategicMerge:
- manager_patch.yaml

namePrefix: extra-large-

commonLabels:
  deployment-size: extra-large

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: beskar7
    app.kubernetes.io/version: v0.2.6
    deployment-size: extra-large

images:
- name: controller
  newName: ghcr.io/wrkode/beskar7/beskar7
  newTag: v0.2.6