apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-manager-pdb
  namespace: beskar7-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      control-plane: controller-manager
      deployment-size: extra-large 