linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - bin
  skip-dirs-use-default: true
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
    - "zz_generated\\..*\\.go$"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - gocyclo
        - dupl

    - path: .*
      linters:
        - depguard

    - linters:
        - gocritic
      text: "unnecessaryDefer:"

    - path: api/
      linters:
        - lll

    - path: zz_generated
      linters:
        - lll

    - path: test/
      text: G402
      linters:
        - gosec

    - path: webhooks/
      linters:
        - lll

    - path: _test\.go
      text: G404
      linters:
        - gosec

    - path: test/
      text: G404
      linters:
        - gosec

    - text: "shadow: declaration of \"err\" shadows declaration"
      linters:
        - govet

    - path: zz_generated
      linters:
        - funlen

    - path: internal/security/monitor\.go
      linters:
        - funlen
    - path: internal/security/rbac_validator\.go
      linters:
        - funlen
    - path: internal/security/tls_validator\.go
      linters:
        - funlen

  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print.*|os\.(Un)?Setenv). is not checked
    - (possible misuse of unsafe.Pointer|should have signature)
    - ineffective break statement. Did you mean to break out of the outer loop
    - G103
    - G204
    - G104

  max-issues-per-linter: 0
  max-same-issues: 0