apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
- service.yaml

namespace: beskar7-system

patches:
- path: patches/cainjection_in_webhooks.yaml
- path: patches/cainjection_in_webhook_configurations.yaml
- path: patches/certmanager_in_webhooks.yaml 