---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: beskar7-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-physicalhost
  failurePolicy: Fail
  name: default.physicalhost.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - physicalhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7machine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: defaulting.beskar7.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7machines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: defaulting.beskar7cluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7machinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: defaulting.beskar7machinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7machinetemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: beskar7-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7machine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.beskar7.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7machines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.beskar7cluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-beskar7machinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.beskar7machinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beskar7machinetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: beskar7-webhook-service
      namespace: beskar7-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-physicalhost
  failurePolicy: Fail
  name: validation.physicalhost.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - physicalhosts
  sideEffects: None
