apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beskar7clusters.infrastructure.cluster.x-k8s.io
  annotations:
    cert-manager.io/inject-ca-from: beskar7-system/beskar7-serving-cert 