apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beskar7machines.infrastructure.cluster.x-k8s.io
  namespace: beskar7-system
spec:
  conversion:
    strategy: None 