apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beskar7clusters.infrastructure.cluster.x-k8s.io
  namespace: beskar7-system
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: beskar7-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1 