# Simple PXE/iPXE Test - Standalone PhysicalHost and Beskar7Machine
#
# This is a minimal example for testing PXE/iPXE functionality without
# deploying a full Cluster API cluster. Use this for initial testing
# and verification of PXE boot configuration.
#
# USAGE:
# 1. Update BMC addresses and credentials below
# 2. Ensure PXE/iPXE infrastructure is running
# 3. Apply: kubectl apply -f pxe-simple-test.yaml
# 4. Watch: kubectl get physicalhost,beskar7machine -n pxe-test -w
# 5. Monitor: kubectl logs -n beskar7-system -l control-plane=controller-manager -f

---
apiVersion: v1
kind: Namespace
metadata:
  name: pxe-test

---
# BMC Credentials
apiVersion: v1
kind: Secret
metadata:
  name: test-bmc-creds
  namespace: pxe-test
type: Opaque
stringData:
  username: "admin"        # Change to your BMC username
  password: "YourPassword" # Change to your BMC password

---
# PhysicalHost for PXE Testing
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PhysicalHost
metadata:
  name: pxe-test-host
  namespace: pxe-test
  labels:
    test: "pxe"
spec:
  redfishConnection:
    address: "https://192.168.1.50"  # Change to your BMC IP
    credentialsSecretRef: test-bmc-creds
    insecureSkipVerify: true         # Use false with proper certs in production

---
# Beskar7Machine using PXE Mode
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Beskar7Machine
metadata:
  name: pxe-test-machine
  namespace: pxe-test
spec:
  # PXE provisioning mode - Beskar7 will configure BMC to boot from network
  provisioningMode: "PXE"
  
  # OS family (for reference)
  osFamily: "flatcar"
  
  # Not used in PXE mode but required by validation
  imageURL: "http://pxe-server.example.com/flatcar.iso"
  
  # Boot mode
  bootMode: "UEFI"

---
# Alternative: Beskar7Machine using iPXE Mode
# Uncomment to test iPXE instead of PXE
#
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: Beskar7Machine
# metadata:
#   name: ipxe-test-machine
#   namespace: pxe-test
# spec:
#   provisioningMode: "iPXE"
#   osFamily: "kairos"
#   imageURL: "http://ipxe-server.example.com/boot.ipxe"
#   bootMode: "UEFI"

---
# Instructions:
#
# After applying this file, monitor the following:
#
# 1. PhysicalHost status:
#    kubectl describe physicalhost pxe-test-host -n pxe-test
#
#    Expected state progression:
#    - None → Enrolling → Available → Claimed → Provisioning
#
# 2. Beskar7Machine status:
#    kubectl describe beskar7machine pxe-test-machine -n pxe-test
#
#    Look for:
#    - PhysicalHostAssociated: True
#    - InfrastructureReady: True
#
# 3. Controller logs:
#    kubectl logs -n beskar7-system -l control-plane=controller-manager -f | grep -i "pxe\|boot"
#
#    You should see:
#    - "Configuring boot for PXE mode"
#    - "Successfully configured PXE boot"
#    - "ensure PXE server is properly configured"
#
# 4. BMC verification (optional):
#    curl -k -u admin:password https://192.168.1.50/redfish/v1/Systems/System.Embedded.1 | jq '.Boot'
#
#    Should show:
#    {
#      "BootSourceOverrideTarget": "Pxe",
#      "BootSourceOverrideEnabled": "Once"
#    }
#
# 5. Physical machine console:
#    - Machine should power on (if off)
#    - Network boot should start
#    - PXE/DHCP requests visible
#    - Boot from network begins
#
# Cleanup:
#    kubectl delete -f pxe-simple-test.yaml

