apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: beskar7-system
spec:
  template:
    spec:
      volumes:
      - name: webhook-server-cert
        secret:
          secretName: beskar7-webhook-server-cert
      containers:
      - name: manager
        volumeMounts:
        - name: webhook-server-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true 