apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: beskar7-system
spec:
  replicas: 2  # Small HA deployment
  template:
    spec:
      containers:
      - name: manager
        args:
        - --leader-elect=true
        - --leader-elect-lease-duration=15s
        - --leader-elect-renew-deadline=10s
        - --leader-elect-retry-period=2s
        - --leader-elect-release-on-cancel=true
        - --enable-security-monitoring=true
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        # Add resources optimized for small deployments
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 50Mi 