---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beskar7-security-policy
  namespace: beskar7-system
  labels:
    app.kubernetes.io/name: beskar7
    app.kubernetes.io/component: security-policy
data:
  policy.yaml: |
    # Beskar7 Security Policy
    # This policy defines security requirements and constraints for Beskar7 components
    
    security:
      # TLS Security Requirements
      tls:
        # Enforce TLS certificate validation by default
        enforce_certificate_validation: true
        
        # Allow insecureSkipVerify only in development environments
        allow_insecure_skip_verify: false
        
        # Minimum TLS version
        min_tls_version: "1.2"
        
        # Certificate expiry warning thresholds
        expiry_warning_days: 30
        expiry_critical_days: 7
        
        # Allowed certificate authorities
        trusted_cas:
          - system # Use system CA bundle
          # - custom-ca-secret # Custom CA from Kubernetes secret
        
        # Certificate validation requirements
        require_hostname_verification: true
        require_valid_certificate_chain: true
        
      # RBAC Security Requirements
      rbac:
        # Principle of least privilege enforcement
        enforce_least_privilege: true
        
        # Prohibited permissions (never allow these)
        prohibited_permissions:
          - apiGroups: ["*"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["rbac.authorization.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - verbs: ["impersonate"]
        
        # Maximum allowed permissions for Beskar7 components
        max_allowed_permissions:
          beskar7-controller:
            - apiGroups: ["infrastructure.cluster.x-k8s.io"]
              resources: ["physicalhosts", "beskar7machines", "beskar7clusters"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["infrastructure.cluster.x-k8s.io"]
              resources: ["physicalhosts/status", "beskar7machines/status", "beskar7clusters/status"]
              verbs: ["get", "update", "patch"]
            - apiGroups: ["cluster.x-k8s.io"]
              resources: ["clusters", "machines"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["create", "patch"]
              
      # Credential Security Requirements
      credentials:
        # Password requirements
        password_policy:
          min_length: 12
          require_uppercase: true
          require_lowercase: true
          require_numbers: true
          require_special_chars: true
          prohibited_common_passwords: true
          
        # Credential rotation requirements
        rotation_policy:
          max_age_days: 90
          warning_age_days: 60
          force_rotation_age_days: 365
          
        # Storage requirements
        storage_policy:
          require_encryption_at_rest: true
          require_kubernetes_secrets: true
          prohibit_plaintext_storage: true
          
        # Access requirements
        access_policy:
          require_audit_logging: true
          limit_access_principals: true
          require_justification: true
          
      # Network Security Requirements
      network:
        # Default to secure communication
        default_tls: true
        
        # Prohibited protocols
        prohibited_protocols:
          - http
          - telnet
          - ftp
          - snmp
          
        # Required encryption for BMC communication
        bmc_encryption: true
        
        # Network policies
        require_network_policies: true
        deny_by_default: true
        
      # Container Security Requirements
      container:
        # Security context requirements
        security_context:
          run_as_non_root: true
          read_only_root_filesystem: true
          allow_privilege_escalation: false
          drop_all_capabilities: true
          seccomp_profile: runtime/default
          
        # Image security requirements
        image_policy:
          require_image_scanning: true
          prohibit_latest_tag: true
          require_signed_images: false # Set to true for production
          allowed_registries:
            - "docker.io"
            - "gcr.io"
            - "quay.io"
            
        # Resource limits (security through resource control)
        resource_limits:
          enforce_resource_limits: true
          default_cpu_limit: "500m"
          default_memory_limit: "512Mi"
          max_cpu_limit: "2000m"
          max_memory_limit: "4Gi"
          
      # Monitoring and Auditing Requirements
      monitoring:
        # Security event monitoring
        security_monitoring:
          enabled: true
          scan_interval: "1h"
          alert_on_critical: true
          alert_on_high: true
          
        # Audit logging requirements
        audit_logging:
          enabled: true
          log_failed_authentications: true
          log_privilege_escalations: true
          log_secret_access: true
          log_rbac_changes: true
          
        # Metrics and alerting
        metrics:
          expose_security_metrics: true
          alert_on_policy_violations: true
          alert_on_certificate_expiry: true
          alert_on_credential_age: true
          
      # Compliance Requirements
      compliance:
        # Standards compliance
        standards:
          cis_kubernetes: true
          nist_cybersecurity: true
          pci_dss: false # Set to true if handling payment data
          soc2: false # Set to true for SOC 2 compliance
          
        # Validation requirements
        validation:
          periodic_security_scans: true
          penetration_testing: false # Set to true for production
          vulnerability_assessments: true
          compliance_reporting: true
          
    # Security exceptions (use sparingly and document thoroughly)
    exceptions:
      # Development environment exceptions
      development:
        allow_insecure_skip_verify: true
        allow_self_signed_certificates: true
        reduced_password_requirements: true
        extended_credential_rotation: true
        
      # Testing environment exceptions  
      testing:
        allow_test_credentials: true
        allow_mock_certificates: true
        relaxed_rbac_validation: true
        
    # Security tools integration
    tools:
      # Static analysis tools
      static_analysis:
        enabled: true
        tools:
          - gosec
          - bandit
          - semgrep
          
      # Dynamic analysis tools
      dynamic_analysis:
        enabled: false # Enable for production
        tools:
          - owasp-zap
          - burp-suite
          
      # Container scanning tools
      container_scanning:
        enabled: true
        tools:
          - trivy
          - clair
          - snyk
          
    # Incident response procedures
    incident_response:
      # Security incident classification
      severity_levels:
        critical:
          - credential_compromise
          - privilege_escalation
          - data_breach
          - system_compromise
        high:
          - authentication_bypass
          - unauthorized_access
          - certificate_compromise
          - configuration_tampering
        medium:
          - policy_violation
          - weak_credentials
          - expired_certificates
          - missing_patches
        low:
          - configuration_drift
          - minor_policy_violations
          - informational_findings
          
      # Response procedures
      procedures:
        automated_response:
          - isolate_compromised_hosts
          - revoke_compromised_credentials
          - alert_security_team
          - generate_incident_report
        manual_response:
          - investigate_incident
          - contain_damage
          - recover_systems
          - conduct_post_incident_review
          
    # Security training and awareness
    training:
      requirements:
        - security_awareness_training
        - secure_coding_practices
        - incident_response_procedures
        - compliance_requirements
        
      frequency:
        security_awareness: quarterly
        technical_training: annually
        compliance_training: annually 