name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  helm-publish:
    name: Package and Publish Helm Chart
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.12.1'

    - name: Package Helm Chart
      run: |
        # Create charts directory for packaging
        mkdir -p .helm-repo
        
        # Package the chart
        helm package charts/beskar7 --destination .helm-repo
        
        # Generate the index
        helm repo index .helm-repo --url https://wrkode.github.io/beskar7

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .helm-repo
        publish_branch: gh-pages
        keep_files: true
