name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  helm-publish:
    name: Package and Publish Helm Chart
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.12.1'

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Package Helm Chart
      run: |
        # Create charts directory for packaging
        mkdir -p .helm-repo
        
        # Package the chart
        helm package charts/beskar7 --destination .helm-repo
        
        # Generate or update the index
        if [ -f .helm-repo/index.yaml ]; then
          helm repo index .helm-repo --merge .helm-repo/index.yaml --url https://wrkode.github.io/beskar7
        else
          helm repo index .helm-repo --url https://wrkode.github.io/beskar7
        fi

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update gh-pages
      run: |
        # Copy new chart packages and index to gh-pages
        cp .helm-repo/*.tgz gh-pages/ || true
        cp .helm-repo/index.yaml gh-pages/
        
        cd gh-pages
        
        # Check if there are changes to commit
        if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -m "Update Helm chart for ${{ github.ref_name }}"
          git push origin gh-pages
        else
          echo "No changes to commit"
        fi

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: gh-pages

  deploy-pages:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: helm-publish
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
